### Create new article
POST http://localhost:3000/api/v1/articles
Content-Type: application/json

{
    "title": "Test Article",
    "description": "This is the content of article 1",
    "author_id": 3
}

### Get all articles
GET http://localhost:3000/api/v1/articles

### Get article by id (replace :id with actual id)
GET http://localhost:3000/api/v1/articles/3

### Update article (replace :id with actual id)
PUT http://localhost:3000/api/v1/articles/2
Content-Type: application/json

{
    "title": "Updated Title",
    "description": "Updated Description"
}

### Delete article (replace :id with actual id)
DELETE http://localhost:3000/api/v1/articles/7


### AUTHORS

### Get all Authors
GET http://localhost:3000/api/v1/authors

### Get Author by ID
GET http://localhost:3000/api/v1/authors/7

### Update author by id
PUT http://localhost:3000/api/v1/authors/2
Content-Type: application/json

{
    "name": "Edgar Allan Poe",
    "email": "Poes_Poetry@poe.com"
}

### Create new Author

POST http://localhost:3000/api/v1/authors
Content-Type: application/json

{
    "name": "J.R.R Tolkien",
    "email": "Hobbits@authors.com"
}

### Delete Author
DELETE http://localhost:3000/api/v1/authors/10
